# For local development only.

name: ${PROJECT_PREFIX:-migrations}

services:
  migrations-dev-8.1:
    container_name: ${PROJECT_PREFIX:-migrations}-dev-8.1
    hostname: ${PROJECT_PREFIX:-migrations}-dev-81
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.1
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  migrations-dev-8.2:
    container_name: ${PROJECT_PREFIX:-migrations}-dev-8.2
    hostname: ${PROJECT_PREFIX:-migrations}-dev-82
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.2
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  migrations-dev-8.3:
    container_name: ${PROJECT_PREFIX:-migrations}-dev-8.3
    hostname: ${PROJECT_PREFIX:-migrations}-dev-83
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.3
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  migrations-dev-8.4:
    container_name: ${PROJECT_PREFIX:-migrations}-dev-8.4
    hostname: ${PROJECT_PREFIX:-migrations}-dev-84
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.4
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  migrations-dev-8.5:
    container_name: ${PROJECT_PREFIX:-migrations}-dev-8.5
    hostname: ${PROJECT_PREFIX:-migrations}-dev-85
    build:
      dockerfile: resources/docker/develop/Dockerfile
      args:
        PHP_VERSION: 8.5
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /srv
    volumes:
      - .:/srv
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    container_name: ${PROJECT_PREFIX:-migrations}-dev-mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=phalcon
      - MYSQL_DATABASE=phalcon
      - MYSQL_PASSWORD=secret
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    container_name: ${PROJECT_PREFIX:-migrations}-dev-postgres
    image: postgres:18-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=phalcon
      - POSTGRES_DB=phalcon
    extra_hosts:
      - "host.docker.internal:host-gateway"
