#!/usr/bin/env php
<?php
declare(strict_types=1);

/**
 * This file is part of the Phalcon Developer Tools.
 *
 * (c) Phalcon Team <team@phalcon.io>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

use Phalcon\Events\Manager as EventsManager;
use Phalcon\Migrations\Console\Color;
use Phalcon\Migrations\Console\Commands\Builtin\Migration;
use Phalcon\Migrations\Console\Commands\CommandsListener;
use Phalcon\Migrations\Console\Script;

try {
    foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
        if (file_exists($file)) {
            require $file;
            break;
        }
    }

    print PHP_EOL . Color::colorize('Phalcon Migrations', Color::FG_GREEN, Color::AT_BOLD) . PHP_EOL . PHP_EOL;

    $eventsManager = new EventsManager();
    $eventsManager->attach('command', new CommandsListener());

    $script = new Script($eventsManager);
    $script->loadUserScripts();
    $script->attach(new Migration($script, $eventsManager));
    $script->run();
} catch (Exception $e) {
    fwrite(STDERR, 'ERROR: ' . $e->getMessage() . PHP_EOL);
    exit(1);
}
