#!/usr/bin/env php
<?php

/**
 * This file is part of the Phalcon Developer Tools.
 *
 * (c) Phalcon Team <team@phalcon.io>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

declare(strict_types=1);

use Phalcon\Cop\Parser;
use Phalcon\Migrations\Console\BuilderException;
use Phalcon\Migrations\Console\Color;
use Phalcon\Migrations\Console\Commands\CommandsException;
use Phalcon\Migrations\Console\Commands\Migration;

try {
    foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
        if (file_exists($file)) {
            require $file;
            break;
        }
    }

    print PHP_EOL . Color::colorize('Phalcon Migrations', Color::FG_GREEN, Color::AT_BOLD) . PHP_EOL . PHP_EOL;

    try {
        $parser = new Parser();
        $parser->parse();
        $command = new Migration($parser);
        $command->run();
    } catch (BuilderException $builderException) {
        echo Color::error($builderException->getMessage());
    } catch (CommandsException $commandsException) {
        echo Color::error($commandsException->getMessage());
    }
} catch (Exception $e) {
    fwrite(STDERR, 'ERROR: ' . $e->getMessage() . PHP_EOL);
    exit(1);
}
