<?php

/**
 * This file is part of the Phalcon Migrations.
 *
 * (c) Phalcon Team <team@phalcon.io>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Phalcon\Migrations\Tests;

use FilesystemIterator;
use PHPUnit\Framework\TestCase;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;

abstract class AbstractTestCase extends TestCase
{
    /**
     * Returns the path to a freshly-created isolated output directory for a test.
     * Any existing directory at that path is removed first.
     */
    protected function getOutputDir(string $path = ''): string
    {
        $dir = $this->getOutputPath($path);
        if (is_dir($dir)) {
            $this->removeDir($dir);
        }
        mkdir($dir, 0755, true);

        return $dir;
    }

    /**
     * Returns the output path without creating or removing anything.
     * Use this to read files already generated by a CLI command or migration run.
     */
    protected function getOutputPath(string $path = ''): string
    {
        return __DIR__ . '/_output/migrations' . ($path ? '/' . ltrim($path, '/') : '');
    }

    protected function removeDir(string $path): void
    {
        if (!is_dir($path)) {
            return;
        }
        $directoryIterator = new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS);
        $iterator          = new RecursiveIteratorIterator($directoryIterator, RecursiveIteratorIterator::CHILD_FIRST);
        foreach ($iterator as $file) {
            if ($file->getFileName() === '.gitignore') {
                continue;
            }
            $realPath = $file->getRealPath();
            $file->isDir() ? rmdir($realPath) : unlink($realPath);
        }
        rmdir($path);
    }
}
